FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
RUN apt update && apt install -y \
    npm \
    curl

# get and install nodejs 
RUN curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - 
RUN apt-get install -y nodejs

RUN apt-get install udev
